# Generated by Django 4.0.6 on 2022-07-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='parent_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
