# Generated by Django 4.0.6 on 2022-07-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_comment_comment_parent_comment_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
