# Generated by Django 4.0.6 on 2022-07-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.room'),
        ),
    ]
