# Generated by Django 4.0.6 on 2022-07-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_comment_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
